/**
 * CloseReading — AI-powered close reading panel.
 * Two modes:
 *   1. Import: Upload a .json file generated by Claude Code (uses Pro plan)
 *   2. API Key: Direct API calls to Claude/OpenAI (uses API credits)
 *
 * Import file format (new per-page format):
 * {
 *   "paperId": "paper_xxx",
 *   "title": "Paper Title",
 *   "results": [
 *     { "startPage": 1, "endPage": 1, "analysis": "markdown..." },
 *     { "startPage": 2, "endPage": 2, "analysis": "..." }
 *   ]
 * }
 *
 * Legacy format (startPage != endPage) is auto-migrated on load.
 * Exposes global window.CloseReading.
 */
(function() {
  const PROVIDER_KEY = "fsi_ai_provider";
  const APIKEY_KEY = "fsi_ai_api_key";
  const ENDPOINT_KEY = "fsi_ai_endpoint";
  const CACHE_KEY = "fsi_cr_cache";

  let _container = null;
  let _getPageText = null;   // async fn(pageNum) => string
  let _getPaperInfo = null;  // fn() => {id, title, numPages}
  let _paperId = null;
  let _results = [];         // [{startPage, endPage, analysis}]
  let _loading = false;
  let _loadingMsg = "";
  let _currentPage = 1;      // current PDF page for sync

  function init(containerEl, opts) {
    _container = containerEl;
    _getPageText = opts.getPageText || null;
    _getPaperInfo = opts.getPaperInfo || null;
  }

  function loadPaper(paperId) {
    _paperId = paperId;
    _results = _loadCache(paperId);
    _loading = false;
  }

  // ── Sync with PDF scroll ─────────────────────────
  function syncScroll(pageNum) {
    _currentPage = pageNum;
    if (!_container) return;
    const listEl = _container.querySelector(".cr-list");
    if (!listEl) return;
    // Highlight active cards and scroll to first match
    const cards = listEl.querySelectorAll(".cr-card");
    let firstMatch = null;
    cards.forEach(card => {
      const sp = parseInt(card.dataset.startpage) || 0;
      const ep = parseInt(card.dataset.endpage) || sp;
      const active = pageNum >= sp && pageNum <= ep;
      card.classList.toggle("active-page", active);
      if (active && !firstMatch) firstMatch = card;
    });
    if (firstMatch) {
      firstMatch.scrollIntoView({ behavior: "smooth", block: "nearest" });
    }
  }

  function resetScrollPosition() {
    if (!window.PdfViewer) return;
    const info = PdfViewer.getCurrentPage();
    syncScroll(info.pageNum);
  }

  function _goToPage(startPage) {
    if (window.PdfViewer) PdfViewer.scrollToPage(startPage, 0);
  }

  // ── Render ───────────────────────────────────────
  function renderPanel() {
    if (!_container) return;
    const info = _getPaperInfo ? _getPaperInfo() : {};
    const hasKey = !!(_getProvider() && _getApiKey());
    const totalPages = info.numPages || 0;
    const coveredPages = _getCoveredPages();
    const hasGap = totalPages > 0 && coveredPages < totalPages;

    let html = '<div class="cr-panel">';

    // Toolbar
    html += '<div class="cr-toolbar">';
    html += '<span style="font-size:12px;color:#94a3b8;font-weight:600">AI 精读</span>';
    if (_results.length > 0) {
      html += '<span style="font-size:11px;color:#475569;margin-left:4px">' + coveredPages + '/' + totalPages + '页</span>';
    }
    html += '<div style="margin-left:auto;display:flex;gap:2px">';
    if (_results.length > 0) {
      html += '<button class="panel-btn" onclick="CloseReading.resetScrollPosition()" title="复位到PDF当前位置">🔄</button>';
    }
    html += '<button class="panel-btn" onclick="CloseReading.triggerImport()" title="导入分析文件">📥</button>';
    html += '<button class="panel-btn" onclick="CloseReading.showSettings()" title="API设置">⚙</button>';
    html += '</div>';
    html += '<input type="file" id="crFileInput" accept=".json,.md,.txt" style="display:none" onchange="CloseReading.handleImport(this)">';
    html += '</div>';

    // Content area — independently scrollable
    html += '<div class="cr-list" id="crList" style="flex:1;overflow-y:auto;padding:4px 0">';

    if (_results.length === 0 && !_loading) {
      // Empty state
      html += '<div style="text-align:center;padding:30px 16px">';
      html += '<div style="font-size:32px;margin-bottom:12px">📖</div>';
      html += '<div style="font-size:13px;color:#f1f5f9;font-weight:600;margin-bottom:16px">论文精读分析</div>';

      html += '<div class="cr-section" style="text-align:left;cursor:pointer" onclick="CloseReading.triggerImport()">';
      html += '<div class="cr-section-title">📥 导入分析文件</div>';
      html += '<div class="cr-section-body" style="font-size:11px;color:#64748b">在 Claude Code 中讨论论文后，导入生成的 .json 精读文件</div>';
      html += '</div>';

      if (hasKey) {
        html += '<div class="cr-section" style="text-align:left;cursor:pointer" onclick="CloseReading.startReading()">';
        html += '<div class="cr-section-title">🤖 全文精读</div>';
        html += '<div class="cr-section-body" style="font-size:11px;color:#64748b">使用 API 逐页分析全文（' + totalPages + ' 页）</div>';
        html += '</div>';
      } else {
        html += '<div class="cr-section" style="text-align:left;cursor:pointer" onclick="CloseReading.showSettings()">';
        html += '<div class="cr-section-title">🔑 配置 API Key</div>';
        html += '<div class="cr-section-body" style="font-size:11px;color:#64748b">配置 OpenAI/Claude API Key 后可在线精读（可选）</div>';
        html += '</div>';
      }
      html += '</div>';
    } else {
      // Show results as cards
      _results.forEach((r, idx) => {
        const sp = r.startPage, ep = r.endPage || sp;
        const pageLabel = sp === ep ? 'P.' + sp : 'P.' + sp + '-' + ep;
        const isActive = _currentPage >= sp && _currentPage <= ep;
        html += '<div class="cr-card' + (isActive ? ' active-page' : '') + '" data-startpage="' + sp + '" data-endpage="' + ep + '" data-idx="' + idx + '" onclick="CloseReading._goToPage(' + sp + ')">';
        html += '<div class="cr-card-header"><span class="cr-page-badge">' + pageLabel + '</span>';
        html += '<button class="panel-btn" onclick="event.stopPropagation();CloseReading.editCard(' + idx + ')" title="编辑" style="margin-left:auto;font-size:10px">✏️</button>';
        html += '<button class="panel-btn" onclick="event.stopPropagation();CloseReading.deleteCard(' + idx + ')" title="删除" style="font-size:10px;color:#f87171">🗑</button>';
        html += '</div>';
        html += '<div class="cr-card-body" ondblclick="event.stopPropagation();CloseReading.editCard(' + idx + ')">' + _formatAnalysis(r.analysis) + '</div>';
        html += '</div>';
      });

      if (_loading) {
        html += '<div class="cr-loading"><div class="spinner"></div><div>' + esc(_loadingMsg || '正在分析...') + '</div></div>';
      }
    }

    html += '</div>';

    // Action bar
    if ((_results.length > 0 || _loading) && !_loading) {
      html += '<div class="cr-action-bar">';
      if (hasKey && hasGap) {
        html += '<button class="cr-continue-btn" onclick="CloseReading.startReading()">🤖 继续精读未覆盖页</button>';
      }
      html += '<button class="cr-continue-btn" onclick="CloseReading.triggerImport()" style="flex:0">📥</button>';
      html += '<button class="cr-continue-btn" onclick="CloseReading.exportResults()" style="flex:0" title="导出结果">📤</button>';
      html += '<button class="cr-continue-btn" onclick="CloseReading.clearResults()" style="flex:0;color:#f87171">🗑</button>';
      html += '</div>';
    }

    html += '</div>';
    _container.innerHTML = html;
  }

  function _getCoveredPages() {
    const pages = new Set();
    _results.forEach(r => {
      for (let p = r.startPage; p <= (r.endPage || r.startPage); p++) pages.add(p);
    });
    return pages.size;
  }

  // ── Import / Export ────────────────────────────────
  function triggerImport() {
    const input = document.getElementById("crFileInput");
    if (input) { input.value = ""; input.click(); }
  }

  function handleImport(input) {
    const file = input.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = function(e) {
      const text = e.target.result;

      if (file.name.endsWith(".json")) {
        try {
          const data = JSON.parse(text);
          if (!data.results || !Array.isArray(data.results)) {
            throw new Error("文件格式错误: 缺少 results 数组");
          }
          // If JSON has a paperId that differs from current, save to the correct paper
          if (data.paperId && data.paperId !== _paperId) {
            const targetId = data.paperId;
            const existing = _loadCache(targetId);
            data.results.forEach(r => {
              if (r.startPage && r.analysis) {
                if (!r.endPage) r.endPage = r.startPage;
                if (typeof r.analysis === "object") r.analysis = _flattenAnalysis(r.analysis);
                const dup = existing.some(x => x.startPage === r.startPage && (x.endPage || x.startPage) === (r.endPage || r.startPage));
                if (!dup) existing.push(r);
              }
            });
            existing.sort((a, b) => a.startPage - b.startPage);
            _saveCache(targetId, existing);
            showToast("✅ 已导入 " + data.results.length + " 段精读到对应论文");
            if (targetId === _paperId) { _results = existing; renderPanel(); }
            if (typeof debouncedPush === "function") debouncedPush("导入精读笔记");
            return;
          }
          _importResults(data.results);
          showToast("✅ 已导入 " + data.results.length + " 段精读分析");
          return;
        } catch(err) {
          showToast("❌ 导入失败: " + err.message);
          return;
        }
      }

      // Markdown / text
      const parsed = _parseMarkdownToResults(text);
      if (parsed.length > 0) {
        _importResults(parsed);
        showToast("✅ 已导入 " + parsed.length + " 段精读分析（Markdown）");
      } else {
        showToast("❌ 导入失败: 未找到 ## Page N 格式的分段");
      }
    };
    reader.readAsText(file);
  }

  function _importResults(results) {
    results.forEach(r => {
      if (r.startPage && r.analysis) {
        if (!r.endPage) r.endPage = r.startPage;
        // If analysis is an object, flatten it to readable markdown
        if (typeof r.analysis === "object") {
          r.analysis = _flattenAnalysis(r.analysis);
        }
        const exists = _results.some(x => x.startPage === r.startPage && (x.endPage || x.startPage) === r.endPage);
        if (!exists) _results.push(r);
      }
    });
    _results.sort((a, b) => a.startPage - b.startPage);
    _saveCache(_paperId, _results);
    renderPanel();
    if (typeof debouncedPush === "function") debouncedPush("导入精读笔记");
  }

  function editCard(idx) {
    if (idx < 0 || idx >= _results.length) return;
    const r = _results[idx];
    const card = _container.querySelector('.cr-card[data-idx="' + idx + '"]');
    if (!card) return;
    const body = card.querySelector('.cr-card-body');
    if (!body || body.querySelector('textarea')) return;

    const ta = document.createElement('textarea');
    ta.className = 'inline-edit-input';
    ta.value = r.analysis || '';
    ta.style.cssText = 'width:100%;min-height:200px;resize:vertical;line-height:1.6;font-size:12px;white-space:pre-wrap;background:#0f172a;border:1px solid #38bdf8;border-radius:4px;padding:6px 8px;color:#e2e8f0;font-family:inherit;outline:none;';
    body.textContent = '';
    body.appendChild(ta);
    ta.focus();

    function save() {
      var v = ta.value.trim();
      if (v !== (r.analysis || '').trim()) {
        _results[idx].analysis = v;
        _saveCache(_paperId, _results);
        if (typeof debouncedPush === 'function') debouncedPush('编辑精读笔记');
      }
      renderPanel();
    }
    ta.addEventListener('blur', save);
    ta.addEventListener('keydown', function(e) {
      if (e.key === 'Enter' && e.ctrlKey) { e.preventDefault(); save(); }
      if (e.key === 'Escape') { renderPanel(); }
    });
    // Prevent card onclick (goToPage) while editing
    ta.addEventListener('click', function(e) { e.stopPropagation(); });
  }

  function deleteCard(idx) {
    if (idx < 0 || idx >= _results.length) return;
    var r = _results[idx];
    var label = r.startPage === (r.endPage || r.startPage) ? 'P.' + r.startPage : 'P.' + r.startPage + '-' + r.endPage;
    if (!confirm('删除 ' + label + ' 的精读笔记？')) return;
    _results.splice(idx, 1);
    _saveCache(_paperId, _results);
    renderPanel();
    if (typeof debouncedPush === 'function') debouncedPush('删除精读笔记');
  }

  /** Recursively flatten a nested analysis object into readable markdown text */
  function _flattenAnalysis(obj, depth) {
    if (depth === undefined) depth = 0;
    if (obj === null || obj === undefined) return "";
    if (typeof obj === "string") return obj;
    if (typeof obj === "number" || typeof obj === "boolean") return String(obj);
    if (Array.isArray(obj)) {
      return obj.map(item => {
        if (typeof item === "string") return "- " + item;
        if (typeof item === "object" && item !== null) {
          // Named items (e.g., paragraphs, figures)
          const label = item.paragraph || item.title || item.figure || item.case || item.reviewer || "";
          let lines = [];
          if (label) lines.push("**" + label + "**");
          for (const [k, v] of Object.entries(item)) {
            if (k === "paragraph" || k === "title" || k === "figure" || k === "case" || k === "reviewer") continue;
            const val = _flattenAnalysis(v, depth + 1);
            if (val) {
              if (typeof v === "string" && v.length < 200) {
                lines.push("- " + _prettifyKey(k) + "：" + val);
              } else {
                lines.push("- **" + _prettifyKey(k) + "**：\n" + val);
              }
            }
          }
          return lines.join("\n");
        }
        return "- " + String(item);
      }).join("\n");
    }
    // Plain object
    let lines = [];
    for (const [k, v] of Object.entries(obj)) {
      const val = _flattenAnalysis(v, depth + 1);
      if (!val) continue;
      if (typeof v === "string") {
        lines.push("**" + _prettifyKey(k) + "**：" + val);
      } else if (Array.isArray(v)) {
        lines.push("**" + _prettifyKey(k) + "**：\n" + val);
      } else if (typeof v === "object") {
        lines.push("**" + _prettifyKey(k) + "**：\n" + val);
      } else {
        lines.push("**" + _prettifyKey(k) + "**：" + val);
      }
    }
    return lines.join("\n");
  }

  function _prettifyKey(key) {
    const map = {
      summary: "摘要", content: "内容", purpose: "目的", citations: "引用",
      keyInsight: "关键洞察", keyPoint: "关键点", keyFindings: "关键发现",
      keyFigures: "关键图表", keyDetail: "关键细节", keyReferences: "关键文献",
      keyThemes: "关键主题", keyDifferences: "关键差异", keyDifference: "关键差异",
      physicalMechanism: "物理机制", physicalExplanation: "物理解释",
      comparisonWithWagnerTheory: "与Wagner理论对比",
      twoWayCouplingEvidence: "双向耦合证据",
      paragraphByParagraph: "逐段分析", subsections: "子节",
      introductionStructure: "Introduction结构", description: "描述",
      insight: "洞察", observation: "观察", interpretation: "解释",
      mainConclusions: "主要结论", futureWork: "未来工作",
      method: "方法", setup: "实验设置", results: "结果",
      limitation: "局限", limitations: "局限性", note: "注意",
      gap: "研究空白", formula: "公式", equation: "方程",
      performance: "性能", novelty: "新颖性", advantage: "优势",
      pattern: "模式", totalCitations: "引用总数", keyGaps: "关键空白",
      AR_effect: "展弦比效应", title: "标题", pages: "页码",
      what: "内容", why: "动机", competitors: "竞品",
      conditions: "条件", fluctuationIntensity: "脉动强度",
      mixing: "混合", jellyfish: "水母态", fingering: "指状",
      edgeVortex: "边缘涡", tipVortex: "翼尖涡",
      directRelevance: "直接相关性", whatYouCanLearn: "可学到的",
      practicalNote: "实践提示", hyperelasticConsideration: "超弹性考虑",
      conceptualRelevance: "概念相关性", possibleInsight: "可能的启发",
      highRelevance: "高度相关", modelAccuracy: "模型精度"
    };
    return map[key] || key.replace(/([A-Z])/g, " $1").replace(/_/g, " ").trim();
  }

  function _parseMarkdownToResults(text) {
    const lines = text.split("\n");
    const results = [];
    let currentPage = null;
    let contentLines = [];

    function flush() {
      if (currentPage !== null && contentLines.length) {
        const analysis = contentLines.join("\n").trim();
        if (analysis) {
          results.push({ startPage: currentPage, endPage: currentPage, analysis });
        }
      }
      contentLines = [];
    }

    for (const line of lines) {
      const pageMatch = line.match(/^##\s+(?:Page\s+|P\.|第)(\d+)/i);
      if (pageMatch) {
        flush();
        currentPage = parseInt(pageMatch[1]);
      } else if (line.startsWith("# ") || line.startsWith("---")) {
        continue;
      } else if (currentPage !== null) {
        const converted = line.replace(/【(.+?)】/g, '**$1**');
        contentLines.push(converted);
      }
    }
    flush();
    return results;
  }

  function exportResults() {
    if (!_results.length) return;
    const info = _getPaperInfo ? _getPaperInfo() : {};
    const data = {
      paperId: _paperId,
      title: info.title || "",
      exportedAt: new Date().toISOString(),
      results: _results
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "精读_" + (info.title || "paper").replace(/[^a-zA-Z0-9\u4e00-\u9fff]/g, "_").slice(0, 40) + ".json";
    a.click();
    URL.revokeObjectURL(a.href);
  }

  // ── Settings UI ────────────────────────────────────
  function showSettings() {
    const listEl = _container ? _container.querySelector(".cr-list") || _container.querySelector("#crList") : null;
    const targetEl = listEl || document.getElementById("crList");
    if (!targetEl) return;
    const provider = _getProvider() || "openai";
    const apiKey = _getApiKey() || "";
    const endpoint = _getEndpoint() || "";
    targetEl.innerHTML = '<div class="cr-setup">' +
      '<div style="font-size:13px;color:#f1f5f9;font-weight:600;margin-bottom:12px">🔑 配置 AI API</div>' +
      '<div class="field"><label>AI 服务商</label>' +
        '<select id="crProvider">' +
          '<option value="openai"' + (provider === "openai" ? " selected" : "") + '>OpenAI (GPT-4o)</option>' +
          '<option value="claude"' + (provider === "claude" ? " selected" : "") + '>Claude (Anthropic)</option>' +
        '</select></div>' +
      '<div class="field"><label>API Key</label>' +
        '<input id="crApiKey" type="password" placeholder="sk-... 或 sk-ant-..." value="' + esc(apiKey) + '"></div>' +
      '<div class="field"><label>自定义 Endpoint (可选)</label>' +
        '<input id="crEndpoint" placeholder="留空使用默认" value="' + esc(endpoint) + '"></div>' +
      '<div class="cr-setup-note">💡 没有 API Key？在 Claude Code 中讨论论文，用 📥 导入分析文件即可。</div>' +
      '<div class="cr-setup-note">⚠️ Claude API 浏览器直连有 CORS 限制，建议用 OpenAI 或配置代理 endpoint。</div>' +
      '<div style="display:flex;gap:8px;margin-top:12px">' +
        '<button class="cr-start-btn" style="flex:1" onclick="CloseReading.saveSettings()">💾 保存</button>' +
        '<button class="cr-continue-btn" onclick="CloseReading.renderPanel()">返回</button>' +
      '</div>' +
    '</div>';
  }

  function saveSettings() {
    const provider = document.getElementById("crProvider").value;
    const apiKey = document.getElementById("crApiKey").value.trim();
    const endpoint = document.getElementById("crEndpoint").value.trim();
    localStorage.setItem(PROVIDER_KEY, provider);
    localStorage.setItem(APIKEY_KEY, apiKey);
    if (endpoint) localStorage.setItem(ENDPOINT_KEY, endpoint); else localStorage.removeItem(ENDPOINT_KEY);
    renderPanel();
  }

  // ── Reading logic (API mode) — full paper, page by page ──
  async function startReading() {
    if (_loading) return;
    const provider = _getProvider();
    const apiKey = _getApiKey();
    if (!provider || !apiKey) { showSettings(); return; }

    const info = _getPaperInfo ? _getPaperInfo() : {};
    if (!info.numPages) return;

    // Find uncovered pages
    const covered = new Set();
    _results.forEach(r => {
      for (let p = r.startPage; p <= (r.endPage || r.startPage); p++) covered.add(p);
    });
    const uncovered = [];
    for (let p = 1; p <= info.numPages; p++) {
      if (!covered.has(p)) uncovered.push(p);
    }
    if (uncovered.length === 0) { showToast("✅ 所有页面已覆盖"); return; }

    _loading = true;
    _loadingMsg = "正在分析第 " + uncovered[0] + " 页 (共 " + uncovered.length + " 页待分析)...";
    renderPanel();

    let completed = 0;
    let prevPageText = "";  // trailing context from previous page
    for (const pageNum of uncovered) {
      _loadingMsg = "正在分析第 " + pageNum + " 页 (" + (completed + 1) + "/" + uncovered.length + ")...";
      _updateLoadingMsg();

      try {
        const pageText = _getPageText ? await _getPageText(pageNum) : "";
        if (!pageText || pageText.trim().length < 20) {
          prevPageText = "";
          completed++;
          continue;
        }
        // Get trailing ~300 chars of previous page as cross-page context
        if (!prevPageText && pageNum > 1) {
          const prevFull = _getPageText ? await _getPageText(pageNum - 1) : "";
          prevPageText = prevFull ? prevFull.trim().slice(-300) : "";
        }
        const prompt = _buildPrompt(info.title, pageNum, pageText, info.numPages, prevPageText);
        const analysis = await _callAI(prompt);
        _results.push({ startPage: pageNum, endPage: pageNum, analysis });
        _results.sort((a, b) => a.startPage - b.startPage);
        _saveCache(_paperId, _results);
        // Keep tail of current page for next iteration
        prevPageText = pageText.trim().slice(-300);
      } catch(e) {
        _results.push({ startPage: pageNum, endPage: pageNum, analysis: "❌ 分析失败: " + e.message });
        break;
      }
      completed++;
    }

    _loading = false;
    renderPanel();
    if (typeof debouncedPush === "function") debouncedPush("AI精读分析");
  }

  function _updateLoadingMsg() {
    const el = _container ? _container.querySelector(".cr-loading div:last-child") : null;
    if (el) el.textContent = _loadingMsg;
  }

  function clearResults() {
    if (!_results.length) return;
    if (!window.confirm("确定清除所有精读分析？（共 " + _results.length + " 段，操作不可撤销）")) return;
    _results = [];
    _clearCache(_paperId);
    renderPanel();
    if (typeof debouncedPush === "function") debouncedPush("清除精读结果");
  }

  // ── Prompt — per page, detailed ────────────────────
  function _buildPrompt(title, pageNum, pageText, totalPages, prevPageText) {
    let contextBlock = "";
    if (prevPageText) {
      contextBlock = `
【上一页末尾内容（用于衔接跨页段落）】：
...${prevPageText}

注意：如果本页开头是上一页未完成段落的延续，请先完成对该段落的分析，再继续分析本页后续段落。不要重复分析上一页已覆盖的内容，只处理跨页衔接部分。

`;
    }
    return `你是一位流固耦合(FSI)领域的学术论文精读助手。
请对以下论文的第 ${pageNum} 页（共 ${totalPages} 页）进行深度逐段分析：

论文标题：${title || "Unknown"}
${contextBlock}第 ${pageNum} 页内容：
${pageText}

请用中文进行精读分析。要求：
1. 逐段落分析，准确对应原文内容
2. 每个段落/小节用 **粗体标题** 标注主题
3. 对关键公式解释物理意义
4. 指出假设条件、适用范围和局限性
5. 标注与其他重要工作（如 Wagner, Korobkin, Faltinsen 等）的联系
6. 如果是图表，描述图表内容和关键信息

请给出全面但精练的分析。不需要分维度，按照原文段落顺序逐一分析即可。`;
  }

  // ── AI API calls ───────────────────────────────────
  async function _callAI(prompt) {
    const provider = _getProvider();
    const apiKey = _getApiKey();
    if (!apiKey) throw new Error("请先配置 API Key");
    if (provider === "claude") return _callClaude(prompt, apiKey);
    return _callOpenAI(prompt, apiKey);
  }

  async function _callOpenAI(prompt, apiKey) {
    const endpoint = _getEndpoint() || "https://api.openai.com/v1/chat/completions";
    const resp = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json", "Authorization": "Bearer " + apiKey },
      body: JSON.stringify({ model: "gpt-4o", messages: [{ role: "user", content: prompt }], max_tokens: 4000, temperature: 0.3 })
    });
    if (!resp.ok) { const err = await resp.text(); throw new Error("OpenAI API " + resp.status + ": " + err.slice(0, 200)); }
    const data = await resp.json();
    return data.choices[0].message.content;
  }

  async function _callClaude(prompt, apiKey) {
    const endpoint = _getEndpoint() || "https://api.anthropic.com/v1/messages";
    const resp = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json", "x-api-key": apiKey, "anthropic-version": "2023-06-01", "anthropic-dangerous-direct-browser-access": "true" },
      body: JSON.stringify({ model: "claude-sonnet-4-20250514", max_tokens: 4000, messages: [{ role: "user", content: prompt }] })
    });
    if (!resp.ok) { const err = await resp.text(); throw new Error("Claude API " + resp.status + ": " + err.slice(0, 200)); }
    const data = await resp.json();
    return data.content[0].text;
  }

  // ── Cache ──────────────────────────────────────────
  function _loadCache(paperId) {
    try { const all = JSON.parse(localStorage.getItem(CACHE_KEY) || "{}"); return all[paperId] || []; } catch(e) { return []; }
  }
  function _saveCache(paperId, results) {
    try {
      const all = JSON.parse(localStorage.getItem(CACHE_KEY) || "{}");
      all[paperId] = results;
      const keys = Object.keys(all);
      if (keys.length > 20) {
        keys.sort((a, b) => (all[a].length || 0) - (all[b].length || 0));
        while (keys.length > 20) { delete all[keys.shift()]; }
      }
      localStorage.setItem(CACHE_KEY, JSON.stringify(all));
    } catch(e) {
      try {
        const fresh = {}; fresh[paperId] = results;
        localStorage.setItem(CACHE_KEY, JSON.stringify(fresh));
      } catch(e2) {}
    }
  }
  function _clearCache(paperId) {
    try { const all = JSON.parse(localStorage.getItem(CACHE_KEY) || "{}"); delete all[paperId]; localStorage.setItem(CACHE_KEY, JSON.stringify(all)); } catch(e) {}
  }

  // ── Helpers ────────────────────────────────────────
  function _getProvider() { return localStorage.getItem(PROVIDER_KEY) || ""; }
  function _getApiKey() { return localStorage.getItem(APIKEY_KEY) || ""; }
  function _getEndpoint() { return localStorage.getItem(ENDPOINT_KEY) || ""; }
  function _formatAnalysis(text) {
    if (!text) return "";
    // If analysis is an object (e.g. loaded from cache before flattening), convert now
    if (typeof text === 'object') text = _flattenAnalysis(text);
    // Enhanced markdown rendering
    let html = esc(text);
    // Headers: # Title → <strong class="cr-h1">
    html = html.replace(/^# (.+)$/gm, '<strong class="cr-h1">$1</strong>');
    // Bold
    html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    // Italic
    html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');
    // Code blocks
    html = html.replace(/```[\s\S]*?```/g, function(m) {
      return '<code class="cr-code">' + m.slice(3, -3).trim() + '</code>';
    });
    // Inline code
    html = html.replace(/`([^`]+)`/g, '<code style="background:#1e293b;padding:1px 4px;border-radius:3px;font-size:12px">$1</code>');
    // Tables (simple | delimited)
    html = html.replace(/\|(.+)\|/g, function(m) {
      const cells = m.split('|').filter(c => c.trim());
      if (cells.every(c => /^[\s-:]+$/.test(c))) return ''; // separator row
      return '<div style="display:flex;gap:8px;font-size:11px;color:#94a3b8">' +
        cells.map(c => '<span style="flex:1">' + c.trim() + '</span>').join('') + '</div>';
    });
    // List items
    html = html.replace(/\n- /g, '<br>• ');
    html = html.replace(/\n(\d+)\.\s/g, '<br>$1. ');
    // Blockquotes
    html = html.replace(/\n&gt;\s?(.+)/g, '<br><span style="border-left:2px solid #38bdf8;padding-left:8px;color:#94a3b8;font-style:italic">$1</span>');
    // Line breaks
    html = html.replace(/\n/g, '<br>');
    return html;
  }

  // ── Expose ─────────────────────────────────────────
  window.CloseReading = {
    init, loadPaper, renderPanel,
    syncScroll, resetScrollPosition, _goToPage,
    startReading, clearResults,
    showSettings, saveSettings,
    triggerImport, handleImport, exportResults,
    editCard, deleteCard
  };
})();
